[package]
name = "readyset"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[target.'cfg(not(target_env="msvc"))'.dependencies]
tikv-jemallocator = "0.4"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.2", features = ["derive","env"] }
futures-util = "0.3.0"
fail = "0.5.0"
failpoint-macros = { path = "../failpoint-macros" }
metrics = "0.19"
metrics-exporter-prometheus = "0.10"
tokio = { workspace = true, features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-stream = { version = "0.1.5", features = ["net"] }
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-subscriber = "0.3.9"
tracing-futures = "0.2.5"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"

# Local dependencies
health-reporter = { path = "../health-reporter" }
readyset-util = { path = "../readyset-util" }
nom-sql = { path = "../nom-sql" }
mysql-srv = { path = "../mysql-srv" }
psql-srv = { path = "../psql-srv" }
database-utils = { path = "../database-utils" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-client = { path = "../readyset-client/" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-data = { path = "../readyset-data" }
readyset-dataflow = { path = "../readyset-dataflow" }
readyset-errors = { path = "../readyset-errors" }
readyset-mongodb = { path = "../readyset-mongodb" }
readyset-mysql = { path = "../readyset-mysql" }
readyset-psql = { path = "../readyset-psql" }
readyset-server = { path = "../readyset-server/" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-version = { path = "../readyset-version" }
replicators = { path = "../replicators" }

[features]
failure_injection = ["fail/failpoints", "readyset-client/failure_injection", "readyset-server/failure_injection"]
fallback_cache = ["readyset-adapter/fallback_cache", "readyset-client-metrics/fallback_cache"]
